services:
  app:
    container_name: ${PROJECT}_php
    image: ${PROJECT}_php:${TAG}
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    # depends_on:
      # - db
    volumes:
      - ./${PROJECT}:/${PROJECT}
    networks:
      - appnet

  server: 
    container_name: ${PROJECT}_nginx
    image: ${PROJECT}_nginx:${TAG}
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - './${PROJECT}:/${PROJECT}'
    networks:
      - appnet

#------------

networks:
  appnet:
    name: ${PROJECT}_net
    driver: bridge
    external: true
      